//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace confop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comite
    {
        public Comite()
        {
            this.MembroComite = new HashSet<MembroComite>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int SiteId { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual ICollection<MembroComite> MembroComite { get; set; }
    }
}
