//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace confop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Site> Site { get; set; }
        public DbSet<Secao> Secao { get; set; }
        public DbSet<Link> Link { get; set; }
        public DbSet<Faq> Faq { get; set; }
        public DbSet<Apoio> Apoio { get; set; }
        public DbSet<Comite> Comite { get; set; }
        public DbSet<MembroComite> MembroComite { get; set; }
        public DbSet<GrupoTrabalho> GrupoTrabalho { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Contato> Contato { get; set; }
    }
}
