//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace confop.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class Secao
    {
        public int Id { get; set; }
        [Required(ErrorMessage="O campo 'Nome' é obrigatório")]
        public string Nome { get; set; }
        
        
        public string Texto { get; set; }
        
        public int SiteId { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
