//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace confop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.Secao = new HashSet<Secao>();
            this.Link = new HashSet<Link>();
            this.Faq = new HashSet<Faq>();
            this.Comite = new HashSet<Comite>();
            this.Apoio = new HashSet<Apoio>();
            this.GrupoTrabalho = new HashSet<GrupoTrabalho>();
            this.Usuario = new HashSet<Usuario>();
            this.Contato = new HashSet<Contato>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Url { get; set; }
        public string Rodape { get; set; }
        public string EmailResponsavel { get; set; }
    
        public virtual ICollection<Secao> Secao { get; set; }
        public virtual ICollection<Link> Link { get; set; }
        public virtual ICollection<Faq> Faq { get; set; }
        public virtual ICollection<Comite> Comite { get; set; }
        public virtual ICollection<Apoio> Apoio { get; set; }
        public virtual ICollection<GrupoTrabalho> GrupoTrabalho { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual ICollection<Contato> Contato { get; set; }
    }
}
